export const ASYNC_START = "ASYNC_START";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const ADD_EVENTS_TO_STORE = "ADD_EVENTS_TO_STORE";
export const SAVE_EVENT_TO_PROFILE = "SAVE_EVENT_TO_PROFILE";
export const DELETE_EVENT_FROM_PROFILE = "DELETE_EVENT_FROM_PROFILE";
