export const ASYNC_START = "ASYNC_START";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const ADD_EVENTS_TO_STORE = "ADD_EVENTS_TO_STORE";
